#
# Travis CI
# A distributed continuous integration service used to build and test projects hosted at GitHub.
#
# https://docs.travis-ci.com/
# https://docs.travis-ci.com/user/getting-started
# https://docs.travis-ci.com/user/customizing-the-build
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs
#
sudo: false
language: node_js
node_js:
  - "6"

cache:
  paths:
    - node_modules
  directories:
    - travis_phantomjs

before_install:
  #
  # upgrade PhantomJS
  # https://github.com/Medium/phantomjs#continuous-integration
  #
  - "export PHANTOMJS_VERSION=2.1.1"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"
